spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: 110755
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: 8080


app:
  jwt:
    secret: "WAwIES1Wv6Lxlv6y0hSaYxtdIe1jubtoYqEqlSBZJYGuoB/83Ru7MTapPnmW7QsJwfIDfICl5ffRmVOfwExkUQ=="
    expiration-ms: 3600000

#jwt:
#  secret: "WAwIES1Wv6Lxlv6y0hSaYxtdIe1jubtoYqEqlSBZJYGuoB/83Ru7MTapPnmW7QsJwfIDfICl5ffRmVOfwExkUQ=="
#  expiration-ms: 3600000
